### ISSUE TITLE
Hapi v17 Support

### ISSUE THREAD

**Issue by timcosta** [ar4mirez/hapi-handlers#4]
### Overview
If you are not aware yet, Hapi v17 is making the transition from callbacks to `async`/`await`, as well as deprecating some other rarely used functionality. This is a breaking change that may make your plugin no longer compatible with the Hapi API.

#### Changelog
Draft release notes can be found here: https://github.com/hapijs/hapi/issues/3658

#### Target Release
The target release date for v17 is the beginning of *November*.

### Tasks
- [x] Reply to this to acknowledge that you are actively maintaining this module and are willing to update it
- [ ] Update plugin to be fully `async`/`await` compatible using the `v17` branch from Hapi for testing
  #### Possible dev flow for updating
  - Clone Hapi
  - `npm link` within the Hapi repo
  - `npm link hapi` within your plugin repo
  - Your plugin will now be using `v17` of Hapi branch for tests
- [ ] Release new major version of your plugin on `npm`. Please use a major version increment as this will be a breaking change and it would be terrible for it to sneak into current versions of Hapi.

### Notes
* Support is being dropped for all versions of Node `<8.0.0`. 
* Hapi `v16` will continue to be supported for as long as there exists a Node LTS actively being supported that is not compatible with `v17`.
* Targeted release date is November 1st, 2017. Please try to have your plugin updated before then.

**Comment by ar4mirez** [comment]
@timcosta acknowledged 👍

**Comment by ar4mirez** [comment]
## Resolved in v4.0.0 🎉

This issue has been addressed with the release of **v4.0.0**, which includes:

- Full **hapi v21+** compatibility (async/await throughout)
- Modern plugin format (`exports.plugin`)
- Updated handler signature using response toolkit (`h`) instead of `reply`
- Node.js 18+ requirement (in line with hapi v21)
- Removed callback-based `async` library (using native async/await)
- Updated `glob` to v10+ with Promise support
- 97% test coverage
- GitHub Actions CI/CD

### Breaking Changes (Migration Guide)

**Handlers must use the new signature:**
```javascript
// Before (hapi v16 and earlier)
module.exports = function (request, reply) {
    reply('Hello World');
};

// After (hapi v17+)
module.exports = function (request, h) {
    return 'Hello World';
    // or: return h.response('Hello World');
};
```

See the [CHANGELOG](https://github.com/ar4mirez/hapi-handlers/blob/master/CHANGELOG.md) and [README](https://github.com/ar4mirez/hapi-handlers/blob/master/README.md#migration-from-v2v3) for full migration details.

Thank you for opening this issue - apologies for the 8-year delay in addressing it! 😅

**Comment by ar4mirez** [comment]
Closing as resolved with v4.0.0 release. The plugin now fully supports hapi v21+ with async/await patterns throughout. See the release notes and migration guide in the README.

**Comment by ar4mirez** [comment]
v4.0.0 has been published to npm! 🎉

Install with:
```bash
npm install hapi-handlers@4.0.0
```

npm: https://www.npmjs.com/package/hapi-handlers
